judge_model: gpt-4.1

bench_name: arena-hard-logs-v3

reference: null

temperature: 0.0
max_tokens: 4096

regex_patterns:
  - \[\[([AB<>=]+)\]\]
  - \[([AB<>=]+)\]

prompt_template: "<|User Prompt|>\n{QUESTION}\n\n<|The Start of Assistant A's Answer|>\n{ANSWER_A}\n<|The End of Assistant A's Answer|>\n\n<|The Start of Assistant B's Answer|>\n{ANSWER_B}\n<|The End of Assistant B's Answer|>"

model_list:
  - gigachat-max
  - gigachat-pro
  - gigachat
  # - gpt-4-0613
  - gpt-4-1106-preview
  - gpt-4.5-preview
  - gpt-4o
